-- Q1. Calculate total sales revenue
SELECT
    SUM(total_amount) AS total_sales
FROM orders;

-- Q2. Count total number of orders
SELECT
    COUNT(*) AS total_orders
FROM orders;

-- Q3. Count total number of customers
SELECT
    COUNT(*) AS total_customers
FROM customers;

-- Q4. Calculate total number of products
SELECT
    COUNT(*) AS total_products
FROM products;


-- Q5. Calculate total revenue by order status
SELECT
    status,
    SUM(total_amount) AS total_revenue
FROM orders
GROUP BY status
ORDER BY total_revenue DESC;


-- Q6. Find average order value
SELECT
    ROUND(AVG(total_amount), 2) AS average_order_value
FROM orders;


-- Q7. Find the highest-value order
SELECT
    order_id,
    customer_id,
    total_amount,
    status
FROM orders
ORDER BY total_amount DESC
LIMIT 1;


-- Q8. Find customers and their total spending
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    SUM(o.total_amount) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_spending DESC;


-- Q9. Find the number of orders placed by each customer
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_orders DESC;


-- Q10. Find total quantity sold for each product
SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_quantity_sold DESC;


-- Q11. Find revenue generated by each product
SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS product_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY product_revenue DESC;


-- Q12. Find revenue generated by each category
SELECT
    c.category_name,
    SUM(oi.quantity * oi.unit_price) AS category_revenue
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY
    c.category_name
ORDER BY category_revenue DESC;


-- Q13. Find the most expensive product
SELECT
    product_id,
    product_name,
    price
FROM products
ORDER BY price DESC
LIMIT 1;


-- Q14. Find products with low stock
SELECT
    product_id,
    product_name,
    stock_quantity
FROM products
WHERE stock_quantity < 20
ORDER BY stock_quantity ASC;


-- Q15. Calculate revenue by payment method
SELECT
    payment_method,
    SUM(amount) AS total_payment_amount
FROM payments
WHERE payment_status = 'Paid'
GROUP BY payment_method
ORDER BY total_payment_amount DESC;


-- Q16. Count orders by payment status
SELECT
    payment_status,
    COUNT(*) AS total_payments
FROM payments
GROUP BY payment_status
ORDER BY total_payments DESC;


-- Q17. Find orders with customer and payment information
SELECT
    o.order_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    o.total_amount,
    o.status,
    p.payment_method,
    p.payment_status
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
JOIN payments p
    ON o.order_id = p.order_id
ORDER BY o.order_id;


-- Q18. Calculate daily sales revenue
SELECT
    DATE(order_date) AS order_date,
    SUM(total_amount) AS daily_revenue
FROM orders
GROUP BY DATE(order_date)
ORDER BY order_date;


-- Q19. Find customers who have spent more than 5000
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    SUM(o.total_amount) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
HAVING SUM(o.total_amount) > 5000
ORDER BY total_spending DESC;